name: Generate ASCII Artwork
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v6

            - name: install cowsay
              run: sudo apt-get update && sudo apt-get install -y cowsay

            - name: Generate ASCII artwork
              run: cowsay -f dragon "Run for cover, the dragon is here!" >> dragon.txt
            - name: sleep for 10 seconds
              run: sleep 10

    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v6

            - name: sleep for 10 seconds
              run: sleep 10

            - name: test file exists
              run: test -f dragon.txt && echo "File exists!" || echo "File does not exist!"

    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v6

            - name: display file content
              run: cat dragon.txt

            - name: deploy file
              run: echo "Deploying dragon.txt to production server..."
