name: Generate ASCII Artwork
on: push
jobs:
    generate_ascii:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v6

            - name: Install cowsay
              run: sudo apt-get install -y cowsay

            - name: Generate ASCII artwork
              run: cowsay -f dragon "Run for cover, the dragon is here!" >> dragon.txt

            - name: Test file file exist
              run: grep -i "dragon" dragon.txt

            - name: Display ASCII artwork
              run: cat dragon.txt
              
            - name: List files
              run: ls -ltra
            
