name: Generate ASCII Artwork
on: push
jobs:
    generate_ascii:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v6

            - name: list file permissions
              run: ls -la

            - name: Execute ASCII script
              run: ./ascii-script.sh
