name: Matrix Configuration Example
on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
                images: [hello-world, nginx:latest]
                exclude:
                    - os: windows-latest
                      images: nginx:latest
        runs-on: ${{ matrix.os }}
        steps:
            - name: Deploy on ${{ matrix.os }}
              run: docker info

            - name: run images on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}
